name: Bloomerang Native Gardens
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55564
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'A native and water wise garden design and maintenance firm. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#201D16'
    - '#88A339'
    - '#FFFFE9'
    - '#E9C6A3'
    - '#7988AC'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
